services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: self_sim_game
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./self-sim-game-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres_user:postgres_password@db:5432/self_sim_game
      # (기존 JSON 로깅 변수는 제거)
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./self-sim-game
      args:
        REACT_APP_API_BASE_URL: ${API_BASE_URL}
    env_file:
      - ./.env
    ports:
      - "3000:80"
    restart: always
volumes:
  db-data:
