version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: self_sim_game
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: ./self-sim-game-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres_user:postgres_password@db:5433/self_sim_game
      # (기존 JSON 로깅 변수는 제거)
    ports:
      - "8000:8000"

volumes:
  db-data:
