spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always   # schema.sql 실행

jwt:
  issuer: base-test
  secret: "this-is-at-least-32-chars-long-secret-for-tests!!"
  access-token-ttl-seconds: 3600

dev:
  h2:
    web-console:
      enabled: false