version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./back
    image: bion0625/ts-backend:v1
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8080"

  frontend:
    build:
      context: ./front
      args:
        VITE_API_URL: http://localhost:8000
    image: bion0625/ts-frontend:v1
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data:
