spring:
  application:
    name: back
  datasource:
    url: jdbc:postgresql://localhost:5433/true_self
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발용 (운영은 validate 또는 none 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true